name: adaptive_theme_fluent_ui
description: An extension package of adaptive_theme library that supports dynamic theming for fluent_ui package.

version: 1.1.0

homepage: https://github.com/birjuvachhani/adaptive_theme_fluent_ui

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: '>=3.2.0 <4.0.0'
  fluent_ui: '>=4.1.0 <5.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true